# Generated by Django 5.0.3 on 2026-03-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', '成员'), ('club_admin', '社团管理员'), ('super_admin', '高级管理员')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='target_role',
            field=models.CharField(blank=True, choices=[('member', '成员'), ('club_admin', '社团管理员'), ('super_admin', '高级管理员')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('president', '社长'), ('vice_president', '副社长')], max_length=32),
        ),
        migrations.CreateModel(
            name='ClubCreationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=128)),
                ('club_intro', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '拒绝'), ('returned', '退回')], default='pending', max_length=16)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_creation_applications', to='club.memberprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
