# Generated by Django 5.0.3 on 2026-03-21 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_memberprofile_role_alter_notice_target_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='launch_approval_status',
            field=models.CharField(choices=[('not_submitted', '草稿未提交审批'), ('pending_super', '待高级管理员审批'), ('approved', '审批通过'), ('rejected', '审批驳回')], default='approved', help_text='新建活动由社长/副社长提交后进入待高级管理员审批；历史数据默认为已通过。', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='launch_review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='launch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='launch_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_launches', to=settings.AUTH_USER_MODEL),
        ),
    ]
