# Generated by Django 5.0.3 on 2026-03-21 20:17
"""多社团外键迁移：为部门、公告、活动、申请和成员资料补充 club 关联并回填旧数据。"""

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_club(apps, schema_editor):
    """把早期单社团数据统一挂到一个默认社团下，保证新增外键不为空。"""

    ClubInfo = apps.get_model("club", "ClubInfo")
    Department = apps.get_model("club", "Department")
    Notice = apps.get_model("club", "Notice")
    Activity = apps.get_model("club", "Activity")
    JoinApplication = apps.get_model("club", "JoinApplication")
    MemberProfile = apps.get_model("club", "MemberProfile")

    default = ClubInfo.objects.order_by("pk").first()
    if not default:
        default = ClubInfo.objects.create(name="默认社团", intro="")
    cid = default.pk

    # 早期表没有 club 字段，这里按默认社团补齐；高级管理员保持无所属社团。
    Department.objects.filter(club__isnull=True).update(club_id=cid)
    Notice.objects.filter(club__isnull=True).update(club_id=cid)
    Activity.objects.filter(club__isnull=True).update(club_id=cid)
    JoinApplication.objects.filter(club__isnull=True).update(club_id=cid)
    MemberProfile.objects.filter(club__isnull=True).update(club_id=cid)
    MemberProfile.objects.filter(role="super_admin").update(club_id=None)


def noop_reverse(apps, schema_editor):
    """数据回填不可安全逆转，迁移回滚时不做反向处理。"""

    pass


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_activity_launch_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='club.clubinfo'),
        ),
        migrations.AddField(
            model_name='department',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='club.clubinfo'),
        ),
        migrations.AddField(
            model_name='joinapplication',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_applications', to='club.clubinfo'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='club',
            field=models.ForeignKey(blank=True, help_text='所属社团；高级管理员通常为空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='club.clubinfo'),
        ),
        migrations.AddField(
            model_name='notice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='club.clubinfo'),
        ),
        migrations.RunPython(backfill_default_club, noop_reverse),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('club', 'name')},
        ),
    ]
