# Generated by Django 5.0.3 on 2026-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_clubmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='club_logos/', verbose_name='标志图片（上传）'),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, upload_to='department_logos/', verbose_name='部门标志'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='标志图片链接'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('president', '社长'), ('vice_president', '副社长'), ('department_head', '部门负责人')], max_length=32),
        ),
    ]
