# Generated by Django 5.0.3 on 2026-03-22 19:40
"""成立社团申请迁移：调整字段中文显示名和申请模型关系。"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_activity_checkin_capacity_joinapplication_simplify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcreationapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_creation_applications', to='club.memberprofile', verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='clubcreationapplication',
            name='club_intro',
            field=models.TextField(blank=True, verbose_name='社团简介'),
        ),
        migrations.AlterField(
            model_name='clubcreationapplication',
            name='club_name',
            field=models.CharField(max_length=128, verbose_name='拟成立社团名称'),
        ),
        migrations.AlterField(
            model_name='clubcreationapplication',
            name='reason',
            field=models.TextField(verbose_name='成立理由'),
        ),
    ]
