# Generated by Django 5.0.3 on 2026-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_club_creation_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='launch_approval_status',
            field=models.CharField(choices=[('not_submitted', '草稿未提交审批'), ('pending_super', '待高级管理员审批'), ('approved', '审批通过'), ('rejected', '审批驳回'), ('not_passed', '未通过审批')], default='approved', help_text='新建活动由社长/副社长提交后进入待高级管理员审批；历史数据默认为已通过。', max_length=20),
        ),
    ]
