# Generated by Django 5.0.3 on 2026-03-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_activity_launch_not_passed_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='full_name',
        ),
    ]
