# Generated by Django 5.0.3 on 2026-03-23 23:58
"""成员资料迁移：移除 full_name，界面展示名改由 display_name 统一生成。"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_activity_launch_not_passed_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='full_name',
        ),
    ]
