# Generated by Django 5.0.3 on 2026-03-24 00:24
"""入社申请迁移：移除 applicant_name，申请人展示改用学号/昵称等字段。"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_memberprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinapplication',
            name='applicant_name',
        ),
    ]
