# Generated by Django 5.0.3 on 2026-03-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_memberprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinapplication',
            name='applicant_name',
        ),
    ]
