# Generated by Django 5.0.3 on 2026-03-26 20:44
"""部门联系方式迁移：为 Department 增加 contact 字段。"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_remove_joinapplication_applicant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact',
            field=models.TextField(blank=True, verbose_name='联系方式'),
        ),
    ]
