from django.urls import path

from . import views

app_name = "club"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("password/reset/", views.reset_password_view, name="reset_password"),
    path("password/change/", views.change_password_view, name="change_password"),
    path("clubs/", views.club_list, name="club_list"),
    path("clubs/<int:pk>/", views.club_detail, name="club_detail"),
    path("club-info/", views.club_info_view, name="club_info"),
    path("club-info/edit/", views.club_info_edit, name="club_info_edit"),
    path("org/", views.org_structure_view, name="org_structure"),
    path("org/departments/", views.department_manage, name="department_manage"),
    path("org/positions/", views.position_manage, name="position_manage"),
    path("notices/", views.notice_list, name="notice_list"),
    path("notices/<int:pk>/", views.notice_detail, name="notice_detail"),
    path("admin/notices/", views.notice_manage, name="notice_manage"),
    path("admin/notices/new/", views.notice_edit, name="notice_new"),
    path("admin/notices/<int:pk>/edit/", views.notice_edit, name="notice_edit"),
    path("admin/notices/<int:pk>/<str:action>/", views.notice_action, name="notice_action"),
    path("activities/", views.activity_list, name="activity_list"),
    path("activities/my/", views.my_activities, name="my_activities"),
    path("activities/<int:pk>/register/", views.activity_register, name="activity_register"),
    path("activities/<int:pk>/cancel/", views.activity_cancel, name="activity_cancel"),
    path("activities/<int:pk>/checkin/", views.activity_checkin, name="activity_checkin"),
    path("admin/activities/", views.activity_manage, name="activity_manage"),
    path("admin/activities/new/", views.activity_edit, name="activity_new"),
    path("admin/activities/<int:pk>/edit/", views.activity_edit, name="activity_edit"),
    path("admin/activities/<int:pk>/<str:action>/", views.activity_action, name="activity_action"),
    path("admin/activities/<int:pk>/submit-launch/", views.activity_submit_launch_approval, name="activity_submit_launch"),
    path("admin/activities/<int:pk>/stats/", views.activity_stats, name="activity_stats"),
    path("admin/leadership/", views.leadership_manage, name="leadership_manage"),
    path("admin/leadership/transfer/", views.leadership_transfer, name="leadership_transfer"),
    path("applications/new/", views.apply_join, name="apply_join"),
    path("applications/my/", views.my_applications, name="my_applications"),
    path("club-create/new/", views.club_creation_apply, name="club_creation_apply"),
    path("club-create/my/", views.my_club_creation_applications, name="my_club_creation_applications"),
    path("admin/applications/", views.application_manage, name="application_manage"),
    path("admin/applications/<int:pk>/<str:action>/", views.application_review, name="application_review"),
    path("super-admin/club-creation/", views.club_creation_manage, name="club_creation_manage"),
    path("super-admin/club-creation/<int:pk>/<str:action>/", views.club_creation_review, name="club_creation_review"),
    path("super-admin/activity-launch/", views.activity_launch_approval_manage, name="activity_launch_approval_manage"),
    path("super-admin/activity-launch/<int:pk>/<str:action>/", views.activity_launch_review, name="activity_launch_review"),
]
